<?php

return [
    'date_filters' => [
        'today' => 'Today',
        'yesterday' => 'Yesterday',
        'this_week' => 'This Week',
        'last_week' => 'Last Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'all_time' => 'All Time',
        'custom' => 'Custom Date Range',
    ],

    'dashboard_cards' => [
        'total_sales' => ['label' => 'Total Sales', 'permission' => 'dashboard.card.total_sales', 'tone' => 'blue'],
        'profit_loss' => ['label' => 'Profit / Loss', 'permission' => 'dashboard.card.profit_loss', 'tone' => 'green'],
        'total_expenses' => ['label' => 'Total Expenses', 'permission' => 'dashboard.card.total_expenses', 'tone' => 'red'],
        'customers_handled' => ['label' => 'Customers Handled', 'permission' => 'dashboard.card.customers_handled', 'tone' => 'sky'],
        'total_orders' => ['label' => 'Total Orders', 'permission' => 'dashboard.card.total_orders', 'tone' => 'indigo'],
        'due_bills' => ['label' => 'Due Bills', 'permission' => 'dashboard.card.due_bills', 'tone' => 'orange'],
        'cash_balance' => ['label' => 'Cash Balance', 'permission' => 'dashboard.card.cash_balance', 'tone' => 'emerald'],
        'bank_balance' => ['label' => 'Bank Balance', 'permission' => 'dashboard.card.bank_balance', 'tone' => 'cyan'],
        'active_tables' => ['label' => 'Today Active Tables', 'permission' => 'dashboard.card.active_tables', 'tone' => 'violet'],
        'hold_orders' => ['label' => 'Hold Orders', 'permission' => 'dashboard.card.hold_orders', 'tone' => 'amber'],
    ],

    'dashboard_charts' => [
        'sales' => ['label' => 'Sales Chart', 'permission' => 'dashboard.chart.sales'],
        'profit_loss' => ['label' => 'Profit / Loss Chart', 'permission' => 'dashboard.chart.profit_loss'],
        'expenses' => ['label' => 'Expense Chart', 'permission' => 'dashboard.chart.expenses'],
        'product_sales' => ['label' => 'Product Sales Chart', 'permission' => 'dashboard.chart.product_sales'],
        'payment_methods' => ['label' => 'Payment Method Chart', 'permission' => 'dashboard.chart.payment_methods'],
    ],

    'modules' => [
        'users' => [
            'label' => 'Users',
            'table' => 'users',
            'icon' => 'U',
            'permission_prefix' => 'users',
            'search' => ['name', 'username', 'phone', 'email'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'username' => ['label' => 'Username', 'type' => 'text', 'required' => true, 'unique' => true],
                'phone' => ['label' => 'Phone Number', 'type' => 'text'],
                'address' => ['label' => 'Address', 'type' => 'textarea'],
                'email' => ['label' => 'Email', 'type' => 'email'],
                'password' => ['label' => 'Password', 'type' => 'password', 'required_on_create' => true],
                'password_confirmation' => ['label' => 'Confirm Password', 'type' => 'password', 'virtual' => true],
                'role_id' => ['label' => 'User Role', 'type' => 'select', 'source' => 'roles', 'required' => true],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'roles' => [
            'label' => 'Roles',
            'table' => 'roles',
            'icon' => 'R',
            'permission_prefix' => 'roles',
            'search' => ['name', 'description'],
            'fields' => [
                'name' => ['label' => 'Role Name', 'type' => 'text', 'required' => true, 'unique' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
                'permissions' => ['label' => 'Permissions', 'type' => 'permissions', 'virtual' => true],
            ],
        ],
        'suppliers' => [
            'label' => 'Suppliers',
            'table' => 'suppliers',
            'icon' => 'S',
            'permission_prefix' => 'suppliers',
            'search' => ['name', 'phone', 'email', 'company_name'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'phone' => ['label' => 'Phone', 'type' => 'text'],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'list' => false],
                'email' => ['label' => 'Email', 'type' => 'email', 'list' => false],
                'company_name' => ['label' => 'Company Name', 'type' => 'text'],
                'opening_balance' => ['label' => 'Opening Balance', 'type' => 'number'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
            'history' => ['Purchases', 'Payments', 'Due amount', 'Return history', 'Purchase total', 'Last purchase date'],
        ],
        'customers' => [
            'label' => 'Customers',
            'table' => 'customers',
            'icon' => 'C',
            'permission_prefix' => 'customers',
            'search' => ['name', 'phone', 'email'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'phone' => ['label' => 'Phone', 'type' => 'text'],
                'address' => ['label' => 'Address', 'type' => 'textarea', 'list' => false],
                'email' => ['label' => 'Email', 'type' => 'email', 'list' => false],
                'default_discount' => ['label' => 'Default Discount', 'type' => 'number'],
                'opening_balance' => ['label' => 'Opening Balance', 'type' => 'number'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
            'history' => ['Sales', 'Due bills', 'Payments', 'Discounts', 'Return history', 'Total spend', 'Last visit'],
        ],
        'categories' => [
            'label' => 'Categories',
            'table' => 'categories',
            'icon' => 'G',
            'permission_prefix' => 'categories',
            'search' => ['name'],
            'fields' => [
                'name' => ['label' => 'Category Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'products' => [
            'label' => 'Products',
            'table' => 'products',
            'icon' => 'P',
            'permission_prefix' => 'products',
            'search' => ['name', 'barcode'],
            'filters' => ['category_id' => 'categories', 'stock_status' => ['All Stock', 'Low Stock', 'Out of Stock']],
            'fields' => [
                'name' => ['label' => 'Product Name', 'type' => 'text', 'required' => true],
                'category_id' => ['label' => 'Category', 'type' => 'select', 'source' => 'categories'],
                'barcode' => ['label' => 'Barcode', 'type' => 'text'],
                'cost_price' => ['label' => 'Cost Price', 'type' => 'number', 'required' => true],
                'selling_price' => ['label' => 'Selling Price', 'type' => 'number', 'required' => true],
                'maintain_stock' => ['label' => 'Maintain Stock', 'type' => 'boolean', 'list' => false],
                'stock_quantity' => ['label' => 'Stock Quantity', 'type' => 'number'],
                'alert_quantity' => ['label' => 'Alert Quantity', 'type' => 'number'],
                'description' => ['label' => 'Description', 'type' => 'textarea', 'list' => false],
                'image_path' => ['label' => 'Product Image', 'type' => 'file', 'list' => false],
                'is_active' => ['label' => 'Active', 'type' => 'boolean', 'list' => false],
            ],
            'history' => ['Sales history', 'Purchase history', 'Stock movement', 'Damage/write-off history', 'Total profit', 'Current stock', 'Alert stock'],
        ],
        'tables' => [
            'label' => 'Tables',
            'table' => 'restaurant_tables',
            'icon' => 'T',
            'permission_prefix' => 'tables',
            'search' => ['number', 'description'],
            'fields' => [
                'number' => ['label' => 'Table Number', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'status' => ['label' => 'Status', 'type' => 'select_static', 'options' => ['available' => 'Available', 'active' => 'Active', 'hold' => 'Hold', 'payment_pending' => 'Payment Pending']],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'waiters' => [
            'label' => 'Waiters',
            'table' => 'waiters',
            'icon' => 'W',
            'permission_prefix' => 'waiters',
            'search' => ['name', 'phone', 'nic'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true],
                'phone' => ['label' => 'Phone', 'type' => 'text'],
                'address' => ['label' => 'Address', 'type' => 'textarea'],
                'nic' => ['label' => 'NIC', 'type' => 'text'],
                'incentive_percentage' => ['label' => 'Incentive Percentage', 'type' => 'number'],
                'is_available' => ['label' => 'Available in POS', 'type' => 'boolean'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
            'history' => ['Tables handled', 'Orders handled', 'Sales amount', 'Profit generated', 'Incentive amount'],
        ],
        'expense_categories' => [
            'label' => 'Expense Categories',
            'table' => 'expense_categories',
            'icon' => 'E',
            'permission_prefix' => 'expense_categories',
            'search' => ['name'],
            'fields' => [
                'name' => ['label' => 'Category Name', 'type' => 'text', 'required' => true],
                'description' => ['label' => 'Description', 'type' => 'textarea'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'expenses' => [
            'label' => 'Expenses',
            'table' => 'expenses',
            'icon' => 'X',
            'permission_prefix' => 'expenses',
            'search' => ['note', 'payment_method'],
            'fields' => [
                'expense_category_id' => ['label' => 'Expense Category', 'type' => 'select', 'source' => 'expense_categories', 'required' => true],
                'amount' => ['label' => 'Amount', 'type' => 'number', 'required' => true],
                'payment_method' => ['label' => 'Payment Method', 'type' => 'select_static', 'options' => ['cash' => 'Cash', 'bank' => 'Bank']],
                'bank_account_id' => ['label' => 'Bank Account', 'type' => 'select', 'source' => 'bank_accounts', 'default' => 'default_bank'],
                'expense_date' => ['label' => 'Date', 'type' => 'datetime-local', 'required' => true, 'default' => 'now'],
                'note' => ['label' => 'Note', 'type' => 'textarea'],
                'attachment_path' => ['label' => 'Attachment', 'type' => 'file'],
            ],
        ],
        'bank_accounts' => [
            'label' => 'Bank Accounts',
            'table' => 'bank_accounts',
            'icon' => 'B',
            'permission_prefix' => 'accounts',
            'search' => ['name', 'account_no'],
            'fields' => [
                'name' => ['label' => 'Account Name', 'type' => 'text', 'required' => true],
                'account_no' => ['label' => 'Account Number', 'type' => 'text'],
                'opening_balance' => ['label' => 'Opening Balance', 'type' => 'number'],
                'is_default' => ['label' => 'Default Account', 'type' => 'boolean'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'online_order_sources' => [
            'label' => 'Online Platforms',
            'table' => 'online_order_sources',
            'icon' => 'O',
            'permission_prefix' => 'online_order_sources',
            'search' => ['name'],
            'fields' => [
                'name' => ['label' => 'Name', 'type' => 'text', 'required' => true, 'unique' => true],
                'commission_type' => ['label' => 'Commission Type', 'type' => 'select_static', 'options' => ['percentage' => 'Percentage', 'fixed' => 'Fixed']],
                'commission_value' => ['label' => 'Commission Value', 'type' => 'number'],
                'is_active' => ['label' => 'Active', 'type' => 'boolean'],
            ],
        ],
        'purchases' => [
            'label' => 'Purchases',
            'table' => 'purchases',
            'icon' => 'B',
            'permission_prefix' => 'purchases',
            'search' => ['reference_no', 'notes'],
            'fields' => [
                'supplier_id' => ['label' => 'Supplier', 'type' => 'select', 'source' => 'suppliers', 'required' => true],
                'reference_no' => ['label' => 'Reference No', 'type' => 'text'],
                'purchase_date' => ['label' => 'Purchase Date', 'type' => 'datetime-local', 'required' => true],
                'subtotal' => ['label' => 'Subtotal', 'type' => 'number'],
                'discount_total' => ['label' => 'Discount', 'type' => 'number'],
                'paid_amount' => ['label' => 'Paid Amount', 'type' => 'number'],
                'due_amount' => ['label' => 'Due Amount', 'type' => 'number'],
                'notes' => ['label' => 'Notes', 'type' => 'textarea'],
            ],
            'history' => ['Supplier details', 'Product details', 'Quantity', 'Cost', 'Discount', 'Payment', 'Due', 'Attachments', 'Stock effect'],
        ],
        'damage_write_offs' => [
            'label' => 'Damage Write-Offs',
            'table' => 'damage_write_offs',
            'icon' => 'D',
            'permission_prefix' => 'damage_write_offs',
            'search' => ['reason', 'note'],
            'fields' => [
                'product_id' => ['label' => 'Product', 'type' => 'select', 'source' => 'products', 'required' => true],
                'quantity' => ['label' => 'Quantity', 'type' => 'number', 'required' => true],
                'reason' => ['label' => 'Reason', 'type' => 'text', 'required' => true],
                'write_off_date' => ['label' => 'Date', 'type' => 'datetime-local', 'required' => true],
                'note' => ['label' => 'Note', 'type' => 'textarea'],
            ],
        ],
        'sales' => [
            'label' => 'Sales',
            'table' => 'sales',
            'icon' => 'L',
            'permission_prefix' => 'sales',
            'search' => ['sales.invoice_no', 'order_tokens.token_number', 'sales.status', 'sales.note'],
            'filters' => ['order_channel' => ['All', 'online', 'pos']],
            'fields' => [
                'invoice_no' => ['label' => 'Invoice No', 'type' => 'text', 'required' => true],
                'customer_id' => ['label' => 'Customer', 'type' => 'select', 'source' => 'customers', 'list' => false],
                'waiter_id' => ['label' => 'Waiter', 'type' => 'select', 'source' => 'waiters'],
                'restaurant_table_id' => ['label' => 'Table', 'type' => 'select', 'source' => 'tables'],
                'sale_date' => ['label' => 'Sale Date', 'type' => 'datetime-local', 'required' => true, 'list' => false],
                'subtotal' => ['label' => 'Subtotal', 'type' => 'number', 'list' => false],
                'discount_amount' => ['label' => 'Discount', 'type' => 'number', 'list' => false],
                'total' => ['label' => 'Total', 'type' => 'number'],
                'paid_amount' => ['label' => 'Paid Amount', 'type' => 'number'],
                'due_amount' => ['label' => 'Due Amount', 'type' => 'number'],
                'profit' => ['label' => 'Profit', 'type' => 'number'],
                'status' => ['label' => 'Status', 'type' => 'select_static', 'options' => ['paid' => 'Paid', 'due' => 'Due', 'deleted' => 'Deleted']],
                'note' => ['label' => 'Note', 'type' => 'textarea', 'list' => false],
            ],
            'history' => ['Sale items', 'Payments', 'Deductions', 'Expense records', 'Stock effect', 'Profit records', 'Waiter incentive', 'Activity log'],
        ],
    ],

    'reports' => [
        'sales' => 'Sales Report',
        'purchases' => 'Purchase Report',
        'profit-loss' => 'Profit & Loss Report',
        'stock' => 'Stock Report',
        'expenses' => 'Expense Report',
        'receive' => 'Receive Report',
        'debit' => 'Debit Report',
        'due-bills' => 'Due Bills Report',
        'customer-due' => 'Customer Due Report',
        'supplier-due' => 'Supplier Due Report',
        'waiters' => 'Waiter Report',
        'product-sales' => 'Product Sales Report',
        'payment-methods' => 'Payment Method Report',
        't-accounts' => 'T Accounts',
        'online-orders' => 'Online Orders Report',
        'register-closing' => 'Register Closing Report',
        'damage-write-offs' => 'Damage Write-Off Report',
        'card-fees' => 'Card Fee Expense Report',
        'qr-payments' => 'QR Payment Report',
        'cash-flow' => 'Cash Flow Report',
    ],

    'permission_categories' => [
        'dashboard' => 'Dashboard',
        'pos' => 'POS',
        'users' => 'Users',
        'roles' => 'Roles',
        'suppliers' => 'Suppliers',
        'customers' => 'Customers',
        'categories' => 'Categories',
        'products' => 'Products',
        'tables' => 'Tables',
        'waiters' => 'Waiters',
        'purchases' => 'Purchases',
        'expenses' => 'Expenses',
        'expense_categories' => 'Expense Categories',
        'damage_write_offs' => 'Damage Write-Offs',
        'accounts' => 'Accounts',
        'online_orders' => 'Online Orders',
        'online_order_sources' => 'Online Platforms',
        'reports' => 'Reports',
        'settings' => 'Settings',
        'activity_logs' => 'Activity Logs',
    ],

    'pos_permissions' => [
        'pos.access' => 'POS access',
        'pos.open_register' => 'Open register',
        'pos.close_register' => 'Close register',
        'pos.add_item' => 'Add item to cart',
        'pos.remove_item' => 'Remove item',
        'pos.change_quantity' => 'Change quantity',
        'pos.line_discount' => 'Add line discount',
        'pos.bill_discount' => 'Add bill discount',
        'pos.hold_order' => 'Hold order',
        'pos.resume_hold_order' => 'Resume hold order',
        'pos.transfer_table' => 'Transfer table',
        'pos.assign_waiter' => 'Assign waiter',
        'pos.remove_waiter' => 'Remove waiter',
        'pos.print_bill' => 'Print bill',
        'pos.payment' => 'Proceed payment',
        'pos.cash_payment' => 'Cash payment',
        'pos.card_payment' => 'Card payment',
        'pos.qr_payment' => 'QR payment',
        'pos.delete_sale' => 'Delete sale',
    ],
];
