<section id="online-order-list" class="pos-card online-panel scroll-mt-24">
    <div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="text-lg font-bold">Track online orders</h3><p class="mt-1 text-sm text-slate-500" data-online-sync>Kitchen status updates automatically. Payment is tracked separately.</p></div><a class="btn-secondary" href="{{ route('online-orders.index') }}#online-order-list">Refresh orders</a></div>
    <form method="GET" action="{{ route('online-orders.index') }}#online-order-list" class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-[2fr_1fr_1fr_1fr_auto]">
        <input name="search" class="form-control" value="{{ request('search') }}" placeholder="Reference, customer or phone" aria-label="Search orders">
        <select name="source_id" class="form-control" aria-label="Filter platform"><option value="all">All platforms</option>@foreach($sources as $source)<option value="{{ $source->id }}" @selected(request('source_id') == $source->id)>{{ $source->name }}</option>@endforeach</select>
        <select name="order_status" class="form-control" aria-label="Filter order status"><option value="all">All order stages</option>@foreach(['new','preparing','ready','out_for_delivery','delivered','cancelled'] as $status)<option value="{{ $status }}" @selected(request('order_status') === $status)>{{ str($status)->replace('_',' ')->headline() }}</option>@endforeach</select>
        <select name="payment_status" class="form-control" aria-label="Filter payment"><option value="all">All payments</option>@foreach(['pending','paid','cash_on_delivery','partially_paid'] as $status)<option value="{{ $status }}" @selected(request('payment_status') === $status)>{{ str($status)->replace('_',' ')->headline() }}</option>@endforeach</select><button class="btn-secondary">Filter</button>
    </form>
    <div class="mt-4 grid gap-3">
        @forelse($orders as $order)
        <article class="online-order-row" data-online-order-id="{{ $order->id }}">
            <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><strong class="text-lg text-slate-900">#{{ str_pad((string) $order->token_number, 2, '0', STR_PAD_LEFT) }}</strong><span class="online-platform-tag">{{ $order->source_name }}</span><span class="online-status" data-order-stage data-stage="{{ $order->order_status }}">{{ str($order->order_status)->replace('_',' ')->headline() }}</span></div><p class="mt-2 break-words text-sm font-semibold">{{ $order->order_reference }} · {{ $order->customer_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $order->customer_phone ?: 'No phone supplied' }} · {{ $order->created_at->format('d M, H:i') }}</p>@if($order->delivery_address)<p class="mt-1 break-words text-xs text-slate-500">{{ $order->delivery_address }}</p>@endif<p class="mt-2 text-xs font-semibold text-slate-600">Kitchen: <span data-order-kitchen>{{ str($order->kitchen_status ?? 'not_sent')->replace('_',' ')->headline() }}</span></p></div>
            <div class="grid content-start gap-1 text-sm"><strong>{{ $currency }} {{ number_format($order->total, 2) }}</strong><span class="text-slate-500" data-order-payment>{{ str($order->payment_status)->replace('_',' ')->headline() }}</span><span class="text-xs text-slate-500">Balance: <b data-order-balance>{{ $currency }} {{ number_format($order->balance_amount, 2) }}</b></span></div>
            <div class="flex flex-wrap items-start gap-2">
                @can('online_orders.print')<a class="btn-secondary !min-h-9 !px-3 !text-xs" href="{{ route('online-orders.print', $order->id) }}" target="_blank" rel="noopener">Print bill</a>@endcan
                @can('online_orders.add_payment')
                @if($order->balance_amount > 0 && $order->order_status !== 'cancelled')<button class="btn-secondary !min-h-9 !px-3 !text-xs" type="button" data-online-payment-open="online-payment-{{ $order->id }}" data-order-pay>Add payment</button>@endif
                @endcan
                @can('online_orders.edit')
                @if(!$order->kitchen_status && in_array($order->order_status, ['new', 'preparing']))<form method="POST" action="{{ route('online-orders.kitchen', $order->id) }}">@csrf<button class="btn-primary !min-h-9 !px-3 !text-xs">Send to kitchen</button></form>@endif
                @if(!in_array($order->order_status, ['cancelled', 'delivered']))
                <form method="POST" action="{{ route('online-orders.status', $order->id) }}" class="flex flex-wrap gap-2" data-online-stage-form>@csrf<select name="order_status" class="form-control !min-h-9 !w-auto !text-xs" data-current="{{ $order->order_status }}" aria-label="Update {{ $order->order_reference }} stage"><option value="{{ $order->order_status }}">{{ str($order->order_status)->replace('_',' ')->headline() }}</option>@foreach((['new' => ['preparing', 'ready', 'cancelled'], 'preparing' => ['ready', 'cancelled'], 'ready' => ['out_for_delivery', 'delivered', 'cancelled'], 'out_for_delivery' => ['delivered', 'cancelled']][$order->order_status] ?? []) as $value)<option value="{{ $value }}">{{ str($value)->replace('_',' ')->headline() }}</option>@endforeach</select><button class="btn-secondary !min-h-9 !px-3 !text-xs">Update</button></form>
                @endif
                @endcan
            </div>
        </article>
        @can('online_orders.add_payment')
        @if($order->balance_amount > 0 && $order->order_status !== 'cancelled')
        <dialog id="online-payment-{{ $order->id }}" class="online-payment-dialog"><div class="online-payment-panel"><button type="button" class="modal-close" data-online-payment-close aria-label="Close payment">×</button><h3 class="text-lg font-bold">Payment · {{ $order->order_reference }}</h3><p class="mt-1 text-sm text-slate-500">Outstanding: {{ $currency }} {{ number_format($order->balance_amount, 2) }}</p><form method="POST" action="{{ route('online-orders.payment', $order->id) }}" class="mt-4 grid gap-3">@csrf<label class="online-label">Amount <input class="form-control" name="amount" type="number" min="0.01" max="{{ $order->balance_amount }}" step="0.01" required></label><label class="online-label">Payment method <select class="form-control" name="payment_method">@foreach(['cash' => 'Cash', 'bank' => 'Bank transfer', 'card' => 'Card', 'online' => 'Online payment', 'platform_payment' => 'Platform payment'] as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="online-label">Payment date <input class="form-control" type="datetime-local" name="payment_date" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label class="online-label">Note <textarea class="form-control" name="note" rows="2"></textarea></label><button class="btn-primary">Save payment</button></form></div></dialog>
        @endif
        @endcan
        @empty<div class="online-cart-empty">No online orders yet.<br><span>Accepted orders will appear here with their kitchen and payment status.</span></div>@endforelse
    </div>
    <div class="mt-4">{{ $orders->links() }}</div>
</section>
<dialog class="kitchen-dialog" data-online-cancel-dialog><form method="dialog" class="p-6"><h3 class="text-xl font-bold">Cancel this online order?</h3><p class="mt-3 text-sm text-slate-600">The kitchen will receive a stop request if preparation is in progress. This reverses the order’s stock and accounting entries. Handle any customer refund through the original payment provider.</p><div class="mt-5 flex justify-end gap-3"><button class="btn-secondary" value="back">Keep order</button><button class="btn-danger" value="confirm">Cancel order</button></div></form></dialog>
